### ISSUE TITLE
[BUG] [Pops][Rachit] Some kind of retry mechanism needed because the Testnet RPC seems to be intermittenly crashing(

### ISSUE THREAD

**Issue by rac-sri** [harmony-one/swoop-testing#22] opened 2020-10-26 09:08 UTC
**Link**
Happened on : https://swoop2.pops.one/

I created a new pool: one/1link.
On swapping using another wallet, the tx confirmation seems a bit random. Sometimes the swap popup keeps loading.

**Reproduce**
Just try swapping one - erc20 multiple times. You should start facing this issue.

**Expected behavior**
All Swaps should happen just fine.

**Screenshots**
![photo_2020-10-26_14-38-01](https://user-images.githubusercontent.com/43861614/97153678-e5096c80-1798-11eb-871a-684763240cd5.jpg)
![photo_2020-10-26_14-38-04](https://user-images.githubusercontent.com/43861614/97153683-e6d33000-1798-11eb-814f-8ba442e98470.jpg)

**Comment by hypnagonia** [comment] 2020-10-27 18:20
ERR_NETWORK_CHANGED indicates network failure. not sure about retries, it can finish off an ill node as well
as a first and simple step I'll add 3-time retry with increasing intervals and a notification with an error and advice to reload the page

**Comment by hypnagonia** [comment] 2020-10-28 11:43
There are few points as fetching lists, images, rpc where outgoing requests happen. Can't gracefully implement retry for all of them. Failed requests are not harmful and ui displays them 

In terms of reading data the app is reactive by design and the situation on the screenshot would have rectified on its own after getblock was available again, wasn't an error

**Comment by chainum** [comment] 2020-10-28 12:37
Ok, let's close it for now and re-open if more users report the same issues.

**Closed as completed by chainum** 2020-10-28 12:37 UTC
Labels: UI, medium priority
