### ISSUE TITLE
[BUG] [POPS] [Soph] LP fees not credited

### ISSUE THREAD

**Issue by sophoah** [harmony-one/swoop-testing#20] opened 2020-10-25 14:15 UTC
**Site/Domain**
swoop3.pops.one

**Describe the bug**
LP fees are not credited

**To Reproduce**
Below to be performed in a controlled environment (no other swap or liquidity provided than the below)
1) Add liquidity with wallet1 to a pair (ie 1SEED/1BUSD) with no liquidity, I have at the end 100% pool share 
2) Swap with wallet2 to that pair, generating an LP fee (ie 3 1SEED)
3) removing the liquidity with wallet1

Compare wallet : wallet1 1SEED and 1BUSD balances at the end are just matching the swap (+ and - of the tokens) and no LP fee added

**Expected behavior**
Fees should be credited and visible after removal

**Screenshot**
![image](https://user-images.githubusercontent.com/35721420/97337689-90124700-18bb-11eb-9ae1-bf68ef432e9a.png)
![image](https://user-images.githubusercontent.com/35721420/97337704-943e6480-18bb-11eb-9dc4-932fcd3d7c53.png)
![image](https://user-images.githubusercontent.com/35721420/97337724-9b657280-18bb-11eb-82d4-cb481a3dc8ec.png)
![image](https://user-images.githubusercontent.com/35721420/97337733-9e606300-18bb-11eb-8f28-d0a11a4bb29c.png)

**Additional context**

**Comment by chainum** [comment] 2020-10-29 12:00
I've been doing multiple tests for this - it seems it happens in some cases, and not every time. It also only seems to happen when it's a brand new pool and for a few of the initial set of trades.

It could be related to the minimum liquidity that is locked by the pool to the pool reserves upon pool creation.

I've done multiple tests on regular Uniswap on Kovan as well, but I haven't had access to any tokens where I can create brand new pools (even obscure testing tokens seems to already have pools there). So haven't been able to fully reproduce this on Uniswap on the Kovan testet.

After discussion with Sahil we'll be closing this for now and re-open if it turns out to be an issue after repeated trading on the launched Swoop version. Swoop is also a tech demo and initial test LP:ers will get incentives from the launch rewards as well besides the LP rewards - so if they miss out on some smaller amount if initial LP funds we've deemed that as ok for now.

Will re-open the ticket if we see more issues like this.

**Closed as completed by chainum** 2020-10-29 12:00 UTC
Labels: smart contracts, need more info, high priority
